//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimationPlayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string StreamLink_hls_segment_threads {
            get {
                return ((string)(this["StreamLink_hls_segment_threads"]));
            }
            set {
                this["StreamLink_hls_segment_threads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("best")]
        public string StreamLink_video_querity {
            get {
                return ((string)(this["StreamLink_video_querity"]));
            }
            set {
                this["StreamLink_video_querity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public string Vlc_file_caching {
            get {
                return ((string)(this["Vlc_file_caching"]));
            }
            set {
                this["Vlc_file_caching"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public string Vlc_network_caching {
            get {
                return ((string)(this["Vlc_network_caching"]));
            }
            set {
                this["Vlc_network_caching"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://i.pinimg.com/originals/ad/4f/a3/ad4fa32b124381aa6bc1e73490748277.gif")]
        public string Animated_Character_Normal_Source {
            get {
                return ((string)(this["Animated_Character_Normal_Source"]));
            }
            set {
                this["Animated_Character_Normal_Source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://4.bp.blogspot.com/-yLL899xkV-A/Wwufve6-2WI/AAAAAAAJlig/QYUS0iS1R98IJjYZ1I" +
            "SEpOgy1r7OCMo1gCLcBGAs/s1600/AW1121058_05.gif")]
        public string Animated_Character_Enter_Source {
            get {
                return ((string)(this["Animated_Character_Enter_Source"]));
            }
            set {
                this["Animated_Character_Enter_Source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1300")]
        public string Chrome_Player_Width {
            get {
                return ((string)(this["Chrome_Player_Width"]));
            }
            set {
                this["Chrome_Player_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("810")]
        public string Chrome_Player_Height {
            get {
                return ((string)(this["Chrome_Player_Height"]));
            }
            set {
                this["Chrome_Player_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emgegpdfcimcmfdplkpbiakpnjhoingk")]
        public string M3u8Player_ID {
            get {
                return ((string)(this["M3u8Player_ID"]));
            }
            set {
                this["M3u8Player_ID"] = value;
            }
        }
    }
}
